# Generated by Django 3.1.4 on 2021-01-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='logo')),
                ('title', models.CharField(max_length=100, verbose_name='About title')),
                ('short_description', models.TextField()),
                ('description', models.TextField(verbose_name='About description')),
                ('image', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client name')),
                ('description', models.TextField(verbose_name='Client description')),
                ('image', models.ImageField(default='default.png', upload_to='clients')),
            ],
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ProjectCategory name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.TextField(verbose_name='service description')),
                ('image', models.ImageField(upload_to='service')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill name')),
                ('level', models.IntegerField(default=0, verbose_name='Skill level')),
            ],
            options={
                'verbose_name': 'Skill name',
                'verbose_name_plural': 'Skills name',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook URL')),
                ('linkedin', models.CharField(max_length=100, verbose_name='Linkedin URL')),
                ('hackerrank', models.CharField(max_length=100, verbose_name='Hackerrank URL')),
                ('github', models.CharField(max_length=100, verbose_name='Github URL')),
            ],
        ),
        migrations.CreateModel(
            name='TotalWorkCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.IntegerField(default=0, verbose_name='Website Count')),
                ('client', models.IntegerField(default=0, verbose_name='Client Count')),
                ('project', models.IntegerField(default=0, verbose_name='Project Count')),
                ('publication', models.IntegerField(default=0, verbose_name='Publication Count')),
            ],
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project title')),
                ('short_description', models.CharField(max_length=150, verbose_name='Project short_description')),
                ('description', models.TextField(verbose_name='Project description')),
                ('image', models.ImageField(upload_to='works')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectcategory')),
            ],
        ),
    ]
