# Generated by Django 3.1.4 on 2021-01-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapLocation',
            new_name='Venue',
        ),
    ]
